/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bdc2ff",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#111d23",
        "surface": "#f4faff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#434750",
        "on-surface-variant": "#454652",
        "secondary-fixed-dim": "#b1cad7",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#181b24",
        "error-container": "#ffdad6",
        "surface-container": "#e3f0f8",
        "primary-fixed": "#e0e0ff",
        "on-secondary-container": "#506873",
        "background": "#f4faff",
        "on-primary-fixed": "#000767",
        "tertiary-container": "#2c3039",
        "surface-container-highest": "#d7e4ec",
        "primary-container": "#1a237e",
        "on-tertiary-container": "#9597a2",
        "surface-container-lowest": "#ffffff",
        "outline": "#767683",
        "inverse-primary": "#bdc2ff",
        "on-primary-container": "#8690ee",
        "tertiary-fixed-dim": "#c4c6d2",
        "surface-bright": "#f4faff",
        "on-primary": "#ffffff",
        "surface-tint": "#4c56af",
        "inverse-on-surface": "#e6f3fb",
        "tertiary": "#181b23",
        "outline-variant": "#c6c5d4",
        "inverse-surface": "#263238",
        "on-primary-fixed-variant": "#343d96",
        "primary": "#000666",
        "tertiary-fixed": "#e0e2ee",
        "surface-variant": "#d7e4ec",
        "secondary-container": "#cde6f4",
        "surface-container-low": "#e9f6fd",
        "on-surface": "#111d23",
        "surface-dim": "#cfdce4",
        "secondary-fixed": "#cde6f4",
        "on-secondary-fixed-variant": "#334a55",
        "secondary": "#4a626d",
        "on-secondary-fixed": "#051e28",
        "surface-container-high": "#ddeaf2",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "4px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "unit": "4px",
        "md": "16px",
        "sm": "8px",
        "xl": "32px",
        "xxl": "48px",
        "max-width": "1440px",
        "lg": "24px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
